Fix ShellCheck error.

diff --git a/tftsrv b/tftsrv
--- a/tftsrv
+++ b/tftsrv
@@ -30,11 +30,11 @@ IFS=$(printf ' \t\n_'); IFS=${IFS%_}
 PATH=/bin:/usr/bin:/usr/local/bin
 export IFS LC_ALL=C LANG=C PATH
 
-readonly progname=${0##*/}
-readonly version=1.1.0.20190405
+readonly progname="${0##*/}"
+readonly version=1.1.1.20220710
 
 # this server application name.
-readonly appname="tftsrv/1.1.0"
+readonly appname="tftsrv/1.1.1"
 
 # There are several implementations named `netcat', and they have different options.
 #
@@ -78,7 +78,7 @@ usage() {
 		    -p  Listen port (usually not needed). Default is $defport
 		    -v  Show program's version number and exit
 	EOT
-    exit $2
+    exit "$2"
 }
 
 # version (no parameter)
@@ -95,7 +95,7 @@ opt=
 while getopts 'f:hp:v' opt; do
     case $opt in
     f)      file=$OPTARG
-            [ "$file" = '-' -o -f "$file" ] || error "$file: Invalid argument"
+            [ "$file" = '-' ] || [ -f "$file" ] || error "$file: Invalid argument"
             ;;
     h)      usage /dev/stdout 0
             ;;
@@ -107,7 +107,7 @@ while getopts 'f:hp:v' opt; do
             ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1))
 
 [ $# -eq 0 ] || usage /dev/stderr 1
 
@@ -121,4 +121,4 @@ shift $(($OPTIND - 1))
     $httpecho "Connection: close\r\n"
     $httpecho "\r\n"
     cat "$file"
-} | $nccmd $port
+} | $nccmd "$port"
diff --git a/tftsrv2 b/tftsrv2
--- a/tftsrv2
+++ b/tftsrv2
@@ -30,11 +30,11 @@ IFS=$(printf ' \t\n_'); IFS=${IFS%_}
 PATH=/bin:/usr/bin:/usr/local/bin
 export IFS LC_ALL=C LANG=C PATH
 
-readonly progname=${0##*/}
-readonly version=1.1.0.20190405
+readonly progname="${0##*/}"
+readonly version=1.1.1.20220710
 
 # this server application name.
-readonly appname="tftsrv2/1.1.0"
+readonly appname="tftsrv2/1.1.1"
 
 # There are several implementations named `netcat', and they have different options.
 #
@@ -76,7 +76,7 @@ usage() {
 		    -p  Listen port (usually not needed). Default is $defport
 		    -v  Show program's version number and exit
 	EOT
-    exit $2
+    exit "$2"
 }
 
 # version (no parameter)
@@ -93,7 +93,7 @@ opt=
 while getopts 'f:hp:v' opt; do
     case $opt in
     f)      file=$OPTARG
-            [ "$file" = '-' -o -f "$file" ] || error "$file: Invalid argument"
+            [ "$file" = '-' ] || [ -f "$file" ] || error "$file: Invalid argument"
             ;;
     h)      usage /dev/stdout 0
             ;;
@@ -105,15 +105,15 @@ while getopts 'f:hp:v' opt; do
             ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift $((OPTIND - 1))
 
 [ $# -eq 0 ] || usage /dev/stderr 1
 
 # read from stdin, then write to temporary file (when need)
 if [ "$file" = '-' ]; then
     trap 'rm -f "$tmpfile"; exit 0' 1 2 15
-    readonly tmpfile=$(mktemp "/tmp/$$-XXXXXXXXXX")
-    [ $? -eq 0 ] || error "cannot create temporary file"
+    tmpfile=$(mktemp "/tmp/$$-XXXXXXXXXX") || error "cannot create temporary file"
+    readonly tmpfile
     cat >"$tmpfile"
     file=$tmpfile
 fi
@@ -129,9 +129,7 @@ while : ; do
         $httpecho "Connection: close\r\n"
         $httpecho "\r\n"
         cat "$file"
-    } | $nccmd $port
-
-    [ $? -eq 0 ] || break
+    } | $nccmd "$port" || break
 done
 
 rm -f "$tmpfile"
